name: Upload Unlocked Package Beta Release

on:
  workflow_call:
    secrets:
      dev-hub-auth-url:
        required: true
      cci-token:
        required: false
    inputs:
      cumulusci-version:
        required: false
        type: string
      sfdx-version:
        required: false
        type: string
      org-name:
        required: false
        type: string
        default: dev
      debug:
        description: 'Display debug logs during Flow Execution'
        required: false
        default: false
        type: boolean

jobs:
  upload-beta-release:
    name: "Upload Beta Release (Unlocked Package)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: project_repo

      - uses: nimba-actions/run-flow-scratch@main
        with:
          dev-hub-auth-url: '${{ secrets.dev-hub-auth-url }}'
          cci-token: '${{ secrets.cci-token }}'
          org-name: '${{ inputs.org-name }}'
          cumulusci-version: '${{ inputs.cumulusci-version }}'
          sfdx-version: '${{ inputs.sfdx-version }}'
          debug: '${{ inputs.debug }}'
          flow-name: release_unlocked_beta
