on:
  workflow_call:
    inputs:
      cumulusci-version:
        required: false
        type: string
      sfdx-version:
        required: false
        type: string
    secrets:
      dev-hub-auth-url:
        required: true

jobs:
  feature-test:
    name: "Feature - Test Unpackaged"
    runs-on: ubuntu-latest
    steps:
      - uses: nimba-actions/feature-test@v1
        with:
          dev-hub-auth-url: '${{ secrets.dev-hub-auth-url }}'
          cumulusci-version: '${{ inputs.cumulusci-version }}'
          sfdx-version: '${{ inputs.sfdx-version }}'
  build-unlocked-test-package:
    name: "Feature - Build Test Package"
    runs-on: ubuntu-latest
    steps:
      - uses: nimba-actions/build-unlocked-test-package@v1
        with:
          dev-hub-auth-url: ${{ secrets.dev-hub-auth-url }}
          cumulusci-version: '${{ inputs.cumulusci-version }}'
          sfdx-version: '${{ inputs.sfdx-version }}'
  feature-test-2gp:
    name: "Feature - Install Test Package"
    runs-on: ubuntu-latest
    needs:
      - build-unlocked-test-package
    steps:
      - uses: nimba-actions/feature-test-2gp@main
        with:
          dev-hub-auth-url: ${{ secrets.dev-hub-auth-url }}
          cumulusci-version: '${{ inputs.cumulusci-version }}'
          sfdx-version: '${{ inputs.sfdx-version }}'
          flow-options: "-o github_package_data__context unlocked_context"

