on:
  workflow_call:
    inputs:
      cumulusci-version:
        required: false
        type: string
      sfdx-version:
        required: false
        type: string
    secrets:
      github-token:
        required: false
      dev-hub-auth-url:
        required: true

jobs:
  feature-test:
    name: "Feature Test"
    runs-on: ubuntu-latest
    steps:
      - uses: nimba-actions/feature-test@main
        with:
          github-token: "${{ inputs.github-token }}"
          dev-hub-auth-url: "${{ secrets.dev-hub-auth-url }}"
          cumulusci-version: "${{ inputs.cumulusci-version }}"
          sfdx-version: "${{ inputs.sfdx-version }}"
