name: Install Beta Release

on:
  workflow_call:
    secrets:
      beta-org-auth-url:
        required: true
    inputs:
      cumulusci-version:
        required: false
        type: string
      sfdx-version:
        required: false
        type: string

jobs:
  install-beta:
    name: "Install Beta Release (Unlocked Package)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup CumulusCI
        uses: nimba-actions/setup-cumulus@v1
        with:
          cumulusci-version: ${{ inputs.cumulusci-version }}

      - name: Authenticate with Target Org
        uses: nimba-actions/authorize-org@v1
        with:
          auth-url: ${{ secrets.beta-org-auth-url }}
          org-name: "beta-org"
          dev-hub: false
      
      - name: Deploy Beta Dependencies
        uses: nimba-actions/run-flow@v1
        with:
          org-name: "beta-org"
          flow-name: ci_beta
