name: Install Beta Release

on:
  workflow_call:
    secrets:
      dev-hub-auth-url:
        required: true
    inputs:
      cumulusci-version:
        required: false
        type: string
      sfdx-version:
        required: false
        type: string
      flow-options:
        required: false
        type: string
      debug:
        description: 'Display debug logs during Flow Execution'
        required: false
        default: false
        type: boolean

jobs:
  install-beta:
    name: "Install Beta Release (Unlocked Package)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup CumulusCI
        uses: nimba-actions/setup-cumulus@v1
        with:
          cumulusci-version: ${{ inputs.cumulusci-version }}

      - name: Deploy Beta Dependencies
        uses: nimba-actions/run-flow-scratch@main
        with:
          dev-hub-auth-url: '${{ secrets.dev-hub-auth-url }}'
          org-name: beta
          cumulusci-version: '${{ inputs.cumulusci-version }}'
          sfdx-version: '${{ inputs.sfdx-version }}'
          debug: '${{ inputs.debug }}'
          flow-options: '${{ inputs.flow-options }}'
          flow-name: ci_beta
        
