on:
  workflow_call:      
    inputs:
      dev-hub-auth-url:
        type: string
        required: true
      cci-token:
        type: string
        required: false
      cumulusci-version:
        required: false
        type: string
      sfdx-version:
        required: false
        type: string
      org-name:
        required: false
        type: string
        default: dev
      debug:
        description: 'Display debug logs during Flow Execution'
        required: false
        default: false
        type: boolean

jobs:
  upload-production-release-2gp:
    name: "Upload Production Release (2GP)"
    environment: packaging-prod
    concurrency: packaging
    runs-on: ubuntu-latest
    steps:
      - uses: nimba-actions/release-production-2gp@main
        with:
          dev-hub-auth-url: '${{ inputs.dev-hub-auth-url }}'
          cci-token: '${{ inputs.cci-token }}'
          cumulusci-version: '${{ inputs.cumulusci-version }}'
          sfdx-version: '${{ inputs.sfdx-version }}'
  release-test:
    name: "Release Test"
    needs:
      - upload-production-release-2gp
    runs-on: ubuntu-latest
    steps: 
      - uses: nimba-actions/release-test@main
        with:
          dev-hub-auth-url: '${{ inputs.dev-hub-auth-url }}'
          cci-token: '${{ inputs.cci-token }}'
          cumulusci-version: '${{ inputs.cumulusci-version }}'
          sfdx-version: '${{ inputs.sfdx-version }}'
