on:
  workflow_call:
    secrets:
      dev-hub-auth-url:
        required: true
      cci-token:
        required: false
    inputs:
      cumulusci-version:
        required: false
        type: string
      sfdx-version:
        required: false
        type: string
      org-name:
        required: false
        type: string
        default: dev
      debug:
        description: 'Display debug logs during Flow Execution'
        required: false
        default: false
        type: boolean

jobs:
  upload-production-release-2gp:
    name: "Upload Production Release (2GP)"
    environment: packaging-prod
    concurrency: packaging
    runs-on: ubuntu-latest
    steps:
      - uses: nimba-actions/release-production-2gp@main
        with:
          dev-hub-auth-url: '${{ secrets.dev-hub-auth-url }}'
  release-test:
    name: "Release Test"
    needs:
      - upload-production-release-2gp
    runs-on: ubuntu-latest
    steps: 
      - uses: nimba-actions/release-test@v1
        with:
          dev-hub-auth-url: '${{ secrets.dev-hub-auth-url }}'
