name: Upload Unlocked Package Production Release

on:
  workflow_call:
    secrets:
      dev-hub-auth-url:
        required: true
      cci-token:
        required: false
      openai-api-key:
        required: false
    inputs:
      cumulusci-version:
        required: false
        type: string
      sfdx-version:
        required: false
        type: string
      debug:
        description: 'Display debug logs during Flow Execution'
        required: false
        default: false
        type: boolean
      org-name:
        required: false
        type: string
        default: dev
      beta-version:
        description: 'The SubscriberPackageVersion (04t) Id for the target package.'
        required: false
        type: string
      

jobs:
  upload-beta-release:
    name: "Upload Production Release (Unlocked Package)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: project_repo

      - uses: nimba-actions/run-flow-scratch@main
        with:
          dev-hub-auth-url: '${{ secrets.dev-hub-auth-url }}'
          cci-token: '${{ secrets.cci-token }}'
          org-name: '${{ inputs.org-name }}'
          debug: '${{ inputs.debug }}'
          sfdx-version: '${{ inputs.sfdx-version }}'
          cumulusci-version: '${{ inputs.cumulusci-version }}'
          flow-name: release_unlocked_production
          flow-options: '--version_id ${{ inputs.beta-version }}'
