name: Upload Unlocked Package Production Release

on:
  workflow_call:
    secrets:
      dev-hub-auth-url:
        required: true
      cci-token:
        required: false
      openai-api-key:
        required: false
    inputs:
      cumulusci-version:
        description: 'CumulusCI version to use'
        required: false
        type: string
      sfdx-version:
        description: 'SFDX version to use'
        required: false
        type: string
      debug:
        description: 'Enable debug mode'
        required: false
        type: boolean

jobs:
  upload-beta-release:
    name: "Upload Production Release (Unlocked Package)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: project_repo
      - uses: nimba-actions/run-flow-scratch@v1 
        with:
          dev-hub-auth-url: '${{ secrets.dev-hub-auth-url }}'
          cumulusci-version: '${{ inputs.cumulusci-version }}'
          sfdx-version: '${{ inputs.sfdx-version }}'
          debug: '${{ inputs.debug }}'
          cci-token: '${{ secrets.cci-token }}'
          org-name: '${{ inputs.org-name }}'
          flow-name: release_unlocked_production
